---
# A pre-commit hook for testing unreleased changes
# Run from tox with: tox -e py39-hook
repos:
  - repo: local
    hooks:
      - id: mdformat-sort
        name: mdformat-from-tox-sort
        entry: mdformat
        args: [--sort-front-matter]
        files: tests/pre-commit-test-(yaml|toml|json)\.md$
        types: [markdown]
        language: system
      - id: mdformat-no-sort
        name: mdformat-from-tox-no-sort
        entry: mdformat
        files: tests/pre-commit-test-yaml-nosort\.md$
        types: [markdown]
        language: system
